### ISSUE TITLE
Version number needs bumping

### ISSUE THREAD

**Issue by andygeers** [icalendar/icalendar-recurrence#12]
Hiya, please could you bump the version number now that there's a fix for convert_duration_to_seconds? Thanks!

**Comment by salex** [comment]
Upgraded a Rails 4.1 application to 4.2.4. That changed version from 1.0.1 to 1.1.0

Now I'm getting:

    undefined method `convert_duration_to_seconds' for #<Icalendar::Recurrence::Schedule:0x007f8dcfdb3008>

Can't seem to find any reference to this problem or the fix that is referenced in this issue.

gems

    icalendar (2.4.0)
    icalendar-recurrence (1.1.0)
      icalendar (~> 2.0)
      ice_cube (~> 0.13.0)
    ice_cube (0.13.3)

**Comment by jnraine** [comment]
Hi all. Apologies for the delay on the release. I've just pushed v1.1.1 to rubygems.org. Let me know if the issue persists!
