### ISSUE TITLE
convert_ice_cube_occurrence should not use "warn"

### ISSUE THREAD

**Issue by graaff** [icalendar/icalendar-recurrence#13]
Currently TZInfo::InvalidTimezoneIdentifier errors are rescued in this method and "warn" is used to output a message. I am using this code in a cron job where I have no influence over the icalendar files I'm processing, and some events have invalid timezone identifiers. The result of this code is that I now get output for each cron run, making the output meaningless. I would rather just handle the errors myself and a way that works for my situation, and I also feel that this would be a good default case here.

The code change would then be to simply remove both the rescue and the warn method. I'd be happy to provide a PR if needed.

Alternatively I suppose the warn could be directed to a logger, or be made optional, but I'm not sure if this if worth the added complexity.

**Comment by rahearn** [comment]
This `warn` just got removed in #37
