### ISSUE TITLE
Loosen ice_cube version dependency

### ISSUE THREAD

**Issue by espen** [icalendar/icalendar-recurrence#15]
Any reason why the gemspec pins ice_cube to ~> 0.13.0? Can this perhaps be changed to <1 to ensure minor upgrades? Ice_cube 0.15.0 is now available https://github.com/seejohnrun/ice_cube/blob/master/CHANGELOG.md

**Comment by jnraine** [comment]
With https://github.com/icalendar/icalendar-recurrence/pull/16, you should now be able to use the latest version of ice_cube.
