### ISSUE TITLE
Push permission to rubygems

### ISSUE THREAD

**Issue by rahearn** [icalendar/icalendar-recurrence#27]
@jnraine can you please grant me access to push new versions of this gem?

`gem owner icalendar-recurrence --add ryan.ahearn@hey.com`

**Comment by hamaron** [comment]
@rahearn @jnraine It would be nice if you guys could publish v.1.1.4, which was supposed to
be available a couple of years ago. I can get my Gemfile point to the master branch, but that's
not ideal.

**Comment by nehresma** [comment]
@jnraine bump on this.  I just lost 4 hours debugging a bug that was already fixed in 1.1.4.

**Comment by rahearn** [comment]
@jnraine any chance you can add me as a gem owner here?

**Comment by nehresma** [comment]
@rahearn, @jnraine works at Stripe -- maybe we'd have more luck trying to reach out to someone at Stripe to ping him.

**Comment by jnraine** [comment]
Hey folks, sorry for missing these pings for 3 years. 🫣

I'm away from my laptop but can grant access tomorrow morning.

**Comment by rahearn** [comment]
No worries, I know my activity has come and go in that time as well.

**Comment by jnraine** [comment]
@rahearn You're now an owner of the gem!

**Comment by rahearn** [comment]
Got it, thank you! For anyone else following along I plan on cutting a new release some time this week

**Comment by nehresma** [comment]
Thank you both!
