### ISSUE TITLE
List tzinfo as runtime dependency

### ISSUE THREAD

**Issue by Pyronix** [icalendar/icalendar-recurrence#30]
Currently, `tzinfo` is [listed as a development dependency](https://github.com/icalendar/icalendar-recurrence/blob/master/icalendar-recurrence.gemspec#L30).

But from its usage in [time_util.rb](https://github.com/icalendar/icalendar-recurrence/blob/master/lib/icalendar/recurrence/time_util.rb#L1) we can see, it should be a runtime dependency.

This will cause issues, when the gem is used in a plain ruby project, where `tzinfo` is not required by `activesupport` for example.

For anyone encountering this issue, you can temporarily fix this by just requiring it alongside this gem yourself:
```ruby
gem 'icalendar-recurrence'
gem 'tzinfo'
```

**Comment by espen** [comment]
Sounds good. Want to make a PR for it?

**Comment by Pyronix** [comment]
> Sounds good. Want to make a PR for it?

I will try to submit one on the weekend, when i have a bit of free time.
