### ISSUE TITLE
Do not fail when rrule is not valid

### ISSUE THREAD

**Issue by espen** [icalendar/icalendar-recurrence#9]
Using invalid RRULE results in ```undefined local variable or method `rrule' for #<Icalendar::Recurrence::Schedule..>```

Will provide a failing test later.

**Comment by jnraine** [comment]
Thanks for the report @espen. Failing tests would be great :ok_hand:.

**Comment by espen** [comment]
https://github.com/espen/icalendar-recurrence/tree/invalid_rrule
